"""Initial tables

Revision ID: ac41ae7f9661
Revises: 
Create Date: 2026-02-10 08:38:01.044169
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac41ae7f9661'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingo_draws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_term', sa.String(length=20), nullable=False),
    sa.Column('draw_datetime', sa.DateTime(), nullable=False),
    sa.Column('numbers', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('sum_total', sa.Integer(), nullable=False),
    sa.Column('odd_count', sa.Integer(), nullable=False),
    sa.Column('sector_1_count', sa.Integer(), nullable=False),
    sa.Column('sector_2_count', sa.Integer(), nullable=False),
    sa.Column('sector_3_count', sa.Integer(), nullable=False),
    sa.Column('sector_4_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bingo_draws_draw_datetime'), 'bingo_draws', ['draw_datetime'], unique=False)
    op.create_index(op.f('ix_bingo_draws_draw_term'), 'bingo_draws', ['draw_term'], unique=True)
    op.create_index('ix_bingo_numbers', 'bingo_draws', ['numbers'], unique=False, postgresql_using='gin')
    op.create_table('daily_cash_draws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_term', sa.String(length=20), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('num_1', sa.Integer(), nullable=False),
    sa.Column('num_2', sa.Integer(), nullable=False),
    sa.Column('num_3', sa.Integer(), nullable=False),
    sa.Column('num_4', sa.Integer(), nullable=False),
    sa.Column('num_5', sa.Integer(), nullable=False),
    sa.Column('numbers_sorted', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('sum_total', sa.Integer(), nullable=False),
    sa.Column('odd_count', sa.Integer(), nullable=False),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_cash_draws_draw_date'), 'daily_cash_draws', ['draw_date'], unique=False)
    op.create_index(op.f('ix_daily_cash_draws_draw_term'), 'daily_cash_draws', ['draw_term'], unique=True)
    op.create_index('ix_daily_cash_numbers_sorted', 'daily_cash_draws', ['numbers_sorted'], unique=False, postgresql_using='gin')
    op.create_table('lotto649_draws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_term', sa.String(length=20), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('num_1', sa.Integer(), nullable=False),
    sa.Column('num_2', sa.Integer(), nullable=False),
    sa.Column('num_3', sa.Integer(), nullable=False),
    sa.Column('num_4', sa.Integer(), nullable=False),
    sa.Column('num_5', sa.Integer(), nullable=False),
    sa.Column('num_6', sa.Integer(), nullable=False),
    sa.Column('special_num', sa.Integer(), nullable=False),
    sa.Column('numbers_sorted', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('sum_total', sa.Integer(), nullable=False),
    sa.Column('odd_count', sa.Integer(), nullable=False),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotto649_draws_draw_date'), 'lotto649_draws', ['draw_date'], unique=False)
    op.create_index(op.f('ix_lotto649_draws_draw_term'), 'lotto649_draws', ['draw_term'], unique=True)
    op.create_index('ix_lotto649_numbers_sorted', 'lotto649_draws', ['numbers_sorted'], unique=False, postgresql_using='gin')
    op.create_table('ml_model_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_model_records_game_type'), 'ml_model_records', ['game_type'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=30), nullable=False),
    sa.Column('target_term', sa.String(length=20), nullable=True),
    sa.Column('predicted_numbers', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('confidence_scores', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('actual_numbers', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_game_type'), 'ml_predictions', ['game_type'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_logs_game_type'), 'scrape_logs', ['game_type'], unique=False)
    op.create_table('super_lotto_draws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_term', sa.String(length=20), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('zone1_num_1', sa.Integer(), nullable=False),
    sa.Column('zone1_num_2', sa.Integer(), nullable=False),
    sa.Column('zone1_num_3', sa.Integer(), nullable=False),
    sa.Column('zone1_num_4', sa.Integer(), nullable=False),
    sa.Column('zone1_num_5', sa.Integer(), nullable=False),
    sa.Column('zone1_num_6', sa.Integer(), nullable=False),
    sa.Column('zone2_num', sa.Integer(), nullable=False),
    sa.Column('zone1_sorted', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('sum_zone1', sa.Integer(), nullable=False),
    sa.Column('odd_count', sa.Integer(), nullable=False),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_lotto_draws_draw_date'), 'super_lotto_draws', ['draw_date'], unique=False)
    op.create_index(op.f('ix_super_lotto_draws_draw_term'), 'super_lotto_draws', ['draw_term'], unique=True)
    op.create_index('ix_super_lotto_zone1_sorted', 'super_lotto_draws', ['zone1_sorted'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_super_lotto_zone1_sorted', table_name='super_lotto_draws', postgresql_using='gin')
    op.drop_index(op.f('ix_super_lotto_draws_draw_term'), table_name='super_lotto_draws')
    op.drop_index(op.f('ix_super_lotto_draws_draw_date'), table_name='super_lotto_draws')
    op.drop_table('super_lotto_draws')
    op.drop_index(op.f('ix_scrape_logs_game_type'), table_name='scrape_logs')
    op.drop_table('scrape_logs')
    op.drop_index(op.f('ix_ml_predictions_game_type'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_ml_model_records_game_type'), table_name='ml_model_records')
    op.drop_table('ml_model_records')
    op.drop_index('ix_lotto649_numbers_sorted', table_name='lotto649_draws', postgresql_using='gin')
    op.drop_index(op.f('ix_lotto649_draws_draw_term'), table_name='lotto649_draws')
    op.drop_index(op.f('ix_lotto649_draws_draw_date'), table_name='lotto649_draws')
    op.drop_table('lotto649_draws')
    op.drop_index('ix_daily_cash_numbers_sorted', table_name='daily_cash_draws', postgresql_using='gin')
    op.drop_index(op.f('ix_daily_cash_draws_draw_term'), table_name='daily_cash_draws')
    op.drop_index(op.f('ix_daily_cash_draws_draw_date'), table_name='daily_cash_draws')
    op.drop_table('daily_cash_draws')
    op.drop_index('ix_bingo_numbers', table_name='bingo_draws', postgresql_using='gin')
    op.drop_index(op.f('ix_bingo_draws_draw_term'), table_name='bingo_draws')
    op.drop_index(op.f('ix_bingo_draws_draw_datetime'), table_name='bingo_draws')
    op.drop_table('bingo_draws')
    # ### end Alembic commands ###
